# Generated by Django 4.2.14 on 2024-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=2, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='fullname',
            field=models.CharField(
                default=1, max_length=100, unique=True, verbose_name='Полное название'
            ),
            preserve_default=False,
        ),
    ]
