# Generated by Django 4.2.14 on 2024-09-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0002_rename_created_at_visitedcountry_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='country.location',
                verbose_name='Расположение',
            ),
        ),
    ]
