# Generated by Django 4.2.14 on 2024-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0002_country_code_country_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='fullname',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='Полное название',
            ),
        ),
    ]
