# Generated by Django 4.2.14 on 2024-09-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0003_alter_country_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='part_of_the_world',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='country.partoftheworld',
                verbose_name='Часть света',
            ),
        ),
    ]
