# Generated by Django 4.2.16 on 2024-12-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0004_alter_location_part_of_the_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_member_of_un',
            field=models.BooleanField(default=False, verbose_name='Является ли членом ООН'),
        ),
        migrations.AddField(
            model_name='country',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='country.country',
            ),
        ),
    ]
