# Generated by Django 4.2.14 on 2024-08-20 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0004_visitedcountry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitedcountry',
            unique_together={('country', 'user')},
        ),
    ]
