# Generated by Django 4.2.16 on 2024-11-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_location_part_of_the_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на-английском языке'),
        ),
        migrations.AlterField(
            model_name='country',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
