# Generated by Django 4.2.16 on 2024-11-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_english_name_alter_country_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на-английском языке'),
        ),
    ]
