# Generated by Django 5.2.12 on 2026-03-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_is_member_of_un_country_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
