# Generated by Django 4.2.16 on 2024-11-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_alter_country_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='english_fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название на-английском языке'),
        ),
    ]
