# Generated by Django 4.2.16 on 2024-11-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0007_country_english_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='code',
            new_name='iso3166_1_alpha2',
        ),
        migrations.AlterField(
            model_name='country',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='country.location',
                verbose_name='Расположение',
            ),
        ),
    ]
