# Generated by Django 4.2.16 on 2024-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_country_english_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='iso3166_1_alpha2',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Двухбуквенный код ISO 3166-1'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3166_1_alpha3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Трехбуквенный код ISO 3166-1'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3166_1_numeric',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Числовой код ISO 3166-1'),
        ),
    ]
