# Generated by Django 4.2.16 on 2024-11-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_alter_visitedcity_rating_and_more'),
        ('country', '0008_remove_country_code_country_iso3166_1_alpha2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city', verbose_name='Столица'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3166_1_alpha3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Трёхбуквенный код ISO 3166-1'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3166_1_numeric',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Цифровой код ISO 3166-1'),
        ),
        migrations.AlterField(
            model_name='country',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.location', verbose_name='Расположение'),
        ),
    ]
