# Generated by Django 4.2.3 on 2023-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_visitedcity_options_alter_visitedcity_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_of_foundation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Численность населения'),
        ),
        migrations.AlterField(
            model_name='city',
            name='wiki',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка на Wikipedia'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='date_of_visit',
            field=models.DateField(blank=True, help_text='Укажите дату посещения города в формате ДД.ММ.ГГГГ. На основе этой даты будет происходить сортировка городов, а также это влияет на отображаемую статистику посещённых городов за год.', null=True, verbose_name='Дата посещения'),
        ),
    ]
