# Generated by Django 4.2.16 on 2024-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0007_alter_visitedcity_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcity',
            name='impression',
            field=models.TextField(blank=True, help_text='В этом поле Вы можете использовать некоторые элементы разметки Markdown, для того, чтобы стилизовать текст.<br>Доступные элементы: заголовки, жирный и курсивный шрифты, ссылки, нумерованные и ненумерованные списки, разделительная линия.', null=True, verbose_name='Впечатления о городе'),
        ),
    ]
