# Generated by Django 4.2.17 on 2025-02-11 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0008_alter_visitedcity_impression'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitedcity',
            unique_together={('user', 'city', 'date_of_visit')},
        ),
        migrations.AddField(
            model_name='visitedcity',
            name='is_first_time',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Первый раз в городе?'),
        ),
    ]
