# Generated by Django 4.2.17 on 2025-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0010_rename_is_first_time_visitedcity_is_first_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcity',
            name='is_first_visit',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True, verbose_name='Первый раз в городе?'),
        ),
    ]
