# Generated by Django 4.2.17 on 2025-02-18 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_alter_visitedcity_is_first_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcity',
            name='date_of_visit',
            field=models.DateField(blank=True, db_index=True, help_text='Укажите дату посещения города в формате ДД.ММ.ГГГГ. На основе этой даты будет происходить сортировка городов, а также это влияет на отображаемую статистику посещённых городов за год.', null=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='rating',
            field=models.SmallIntegerField(db_index=True, help_text='Поставьте оценку городу. 1 - плохо, 5 - отлично.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
