# Generated by Django 4.2.17 on 2025-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_alter_visitedcity_date_of_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
    ]
