# Generated by Django 4.2.20 on 2025-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Ссылка на изображение'),
        ),
    ]
