# Generated by Django 4.2.21 on 2025-05-24 09:33

from django.db import migrations, models


def set_source_image(apps, schema_editor):
    model = apps.get_model('city', 'City')

    for city in model.objects.all():
        if city.image:
            city.image_source_text = "ВКонтакте-сообщество 'Городские открытки'"
            city.image_source_link = 'https://vk.com/city_postcard_2023'
            city.save()


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0014_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_source_link',
            field=models.URLField(
                blank=True, null=True, verbose_name='Ссылка на источник изображения'
            ),
        ),
        migrations.AddField(
            model_name='city',
            name='image_source_text',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Название источника изображения'
            ),
        ),
        migrations.RunPython(set_source_image),
    ]
