# Generated by Django 4.2.21 on 2025-06-06 09:59

from django.db import migrations, models
import django.db.models.deletion

from city.models import City
from country.models import Country


def set_country(apps, schema_editor):
    try:
        City.objects.all().update(country=Country.objects.get(pk=171))
    except:
        ...


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0005_country_is_member_of_un_country_owner'),
        ('city', '0015_city_image_source_link_city_image_source_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='country.country',
                verbose_name='Страна',
            ),
        ),
        migrations.RunPython(set_country),
    ]
