# Generated by Django 4.2.21 on 2025-06-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_is_member_of_un_country_owner'),
        ('city', '0016_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country', verbose_name='Страна'),
        ),
    ]
