# Generated by Django 4.2.21 on 2025-06-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0017_alter_city_country_alter_city_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedcity',
            name='region',
        ),
    ]
