# Generated by Django 4.2.24 on 2025-12-02 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_create_city_AB'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedcity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='visitedcity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
    ]
