# Generated by Django 4.2.24 on 2025-12-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0020_add_timestamps_to_visited_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
