# Generated by Django 4.2.24 on 2025-12-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0021_change_created_at_to_auto_now_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityListDefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('filter', 'Фильтрация'), ('sort', 'Сортировка')], max_length=10, verbose_name='Тип параметра')),
                ('parameter_value', models.CharField(help_text='Значение фильтра или сортировки, аналогичное тем, что указаны в панели фильтрации и сортировки.', max_length=50, verbose_name='Значение параметра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка по умолчанию списка городов',
                'verbose_name_plural': 'Настройки по умолчанию списка городов',
                'ordering': ['user', 'parameter_type'],
                'unique_together': {('user', 'parameter_type')},
            },
        ),
    ]
