# Generated by Django 4.2.24 on 2026-01-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0022_citylistdefaultsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Площадь района в квадратных километрах', max_digits=10, null=True, verbose_name='Площадь')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Численность населения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='city.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район города',
                'verbose_name_plural': 'Районы городов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VisitedCityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField(blank=True, db_index=True, help_text='Дата посещения района. Можно оставить пустым, но для одного района у одного пользователя может быть только одна запись без даты.', null=True, verbose_name='Дата посещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('city_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='city.citydistrict', verbose_name='Район города')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_city_districts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещённый район города',
                'verbose_name_plural': 'Посещённые районы городов',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='visitedcitydistrict',
            constraint=models.UniqueConstraint(condition=models.Q(('date_of_visit__isnull', True)), fields=('user', 'city_district'), name='unique_user_city_district_without_date'),
        ),
        migrations.AlterUniqueTogether(
            name='visitedcitydistrict',
            unique_together={('user', 'city_district', 'date_of_visit')},
        ),
        migrations.AlterUniqueTogether(
            name='citydistrict',
            unique_together={('title', 'city')},
        ),
    ]
