# Generated by Django 4.2.24 on 2026-01-12 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0023_add_city_district_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visitedcitydistrict',
            name='unique_user_city_district_without_date',
        ),
        migrations.AlterUniqueTogether(
            name='visitedcitydistrict',
            unique_together={('user', 'city_district')},
        ),
        migrations.RemoveField(
            model_name='visitedcitydistrict',
            name='date_of_visit',
        ),
    ]
