# Generated by Django 4.2.24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0024_remove_date_of_visit_from_visited_city_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMapColorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_visited', models.CharField(blank=True, help_text='Цвет в формате #rrggbb', max_length=7, null=True, verbose_name='Цвет посещённых районов')),
                ('color_not_visited', models.CharField(blank=True, help_text='Цвет в формате #rrggbb', max_length=7, null=True, verbose_name='Цвет непосещённых районов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='district_map_color_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки цветов карты районов',
                'verbose_name_plural': 'Настройки цветов карты районов',
            },
        ),
    ]
