# Generated by Django 4.2.24

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0025_districtmapcolorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,
                verbose_name='Дата и время создания',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                default=timezone.now,
                verbose_name='Дата и время изменения',
            ),
            preserve_default=False,
        ),
    ]
