# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0026_districtmapcolorsettings_created_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='color_border',
            field=models.CharField(
                blank=True,
                help_text='Цвет в формате #rrggbb',
                max_length=7,
                null=True,
                verbose_name='Цвет границ полигонов',
            ),
        ),
    ]
