# Generated by Django 4.2.24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0027_districtmapcolorsettings_color_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='border_weight',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Ширина границ полигонов от 1 до 10 пикселей',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name='Ширина границ (px)',
            ),
        ),
    ]
