# Generated by Django 4.2.24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0028_districtmapcolorsettings_border_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='fill_opacity_visited',
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text='Прозрачность заливки посещённых районов, 0–100',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='Прозрачность заливки посещённых (%)',
            ),
        ),
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='fill_opacity_not_visited',
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text='Прозрачность заливки непосещённых районов, 0–100',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='Прозрачность заливки непосещённых (%)',
            ),
        ),
        migrations.AddField(
            model_name='districtmapcolorsettings',
            name='border_opacity',
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text='Прозрачность границ полигонов, 0–100',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name='Прозрачность границ (%)',
            ),
        ),
    ]
