# Generated by Django 4.2.24 on 2026-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0029_districtmapcolorsettings_opacity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcity',
            name='impression',
            field=models.TextField(blank=True, help_text='В этом поле Вы можете использовать некоторые элементы разметки Markdown, для того, чтобы стилизовать текст. Доступные элементы: заголовки, жирный и курсивный шрифты, ссылки, нумерованные и ненумерованные списки, разделительная линия.', null=True, verbose_name='Впечатления о городе'),
        ),
    ]
