# Generated by Django 5.2.12 on 2026-05-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSMPolygonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.BigIntegerField(unique=True, verbose_name='Nominatim relation ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название объекта')),
                ('geojson', models.JSONField(verbose_name='GeoJSON полигона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'OSM полигон',
                'verbose_name_plural': 'OSM полигоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
