# Generated by Django 4.2.3 on 2024-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharesettings',
            old_name='switch_share_general',
            new_name='can_share',
        ),
        migrations.RenameField(
            model_name='sharesettings',
            old_name='switch_share_basic_info',
            new_name='can_share_basic_info',
        ),
        migrations.RenameField(
            model_name='sharesettings',
            old_name='switch_share_city_map',
            new_name='can_share_city_map',
        ),
        migrations.RenameField(
            model_name='sharesettings',
            old_name='switch_share_region_map',
            new_name='can_share_region_map',
        ),
    ]
