# Generated by Django 4.2.13 on 2024-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_rename_can_share_basic_info_sharesettings_can_share_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesettings',
            name='can_subscribe',
            field=models.BooleanField(
                blank=True, default=False, verbose_name='Разрешить подписываться'
            ),
        ),
    ]
