# Generated by Django 4.2.21 on 2025-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharesettings',
            options={'verbose_name': 'Параметры публикации статистики', 'verbose_name_plural': 'Параметры публикации статистики'},
        ),
    ]
