# Generated by Django 5.2.12 on 2026-03-27 10:57

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_sharesettings_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userconsent',
            options={'verbose_name': 'Согласие пользователя', 'verbose_name_plural': 'Согласия пользователей'},
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='consent_given',
            field=models.BooleanField(default=True, verbose_name='Согласие дано'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='consent_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время согласия'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='policy_version',
            field=models.CharField(max_length=10, verbose_name='Версия политики'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
