"""
----------------------------------------------

Copyright © Egor Vavilov (Shecspi)
Licensed under the Apache License, Version 2.0

----------------------------------------------
"""

from django.urls import include
from dmr.routing import Router, path
from dashboard.api import (
    GetBlogArticlesByPageController,
    GetBlogArticlesAddedByRangeController,
    GetBlogArticlesAddedComparisonController,
    GetBlogArticlesViewsByRangeController,
    GetBlogArticlesViewsComparisonController,
    GetBlogArticlesViewsTotalController,
    GetBlogLastAddedArticlesController,
    GetBlogTopViewedArticlesController,
    GetPersonalCollectionsByRangeController,
    GetPersonalCollectionsComparisonController,
    GetPersonalCollectionsTotalController,
    GetPlacesByRangeController,
    GetPlacesComparisonController,
    GetPublicPersonalCollectionsTotalController,
    GetTotalVisitedPlacesController,
    GetTotalVisitedOnlyPlacesController,
    GetAddedVisitedCountriesByRangeController,
    GetAddedVisitedCountriesComparisonController,
    GetAddedVisitedCitiesByRangeController,
    GetAddedVisitedCitiesComparisonController,
    GetNumberOfUsersController,
    GetRegistrationsByRangeController,
    GetRegistrationsComparisonController,
    GetRegistrationsCumulativeChartController,
    GetTotalVisitedCitiesVisitsController,
    GetUniqueVisitedCitiesController,
    GetMaxQtyUniqueVisitedCitiesController,
    GetMaxQtyVisitedCitiesController,
    GetNumberOfUsersWithoutVisitedCitiesController,
    GetAverageQtyVisitedCitiesController,
    GetAverageQtyUniqueVisitedCitiesController,
    GetTotalVisitedCountriesController,
    GetUsersWithVisitedCountriesController,
    GetAverageQtyVisitedCountriesController,
    GetAddedVisitedCountryController,
    GetMaxQtyVisitedCountriesController,
    GetAddedVisitedCountriesChartController,
    GetVisitedCitiesByUserChartController,
    GetUniqueVisitedCitiesByUserChartController,
)

router = Router(
    'api/dashboard',
    [
        path(
            'users/',
            GetNumberOfUsersController.as_view(),
        ),
        path(
            'users/registrations/range/',
            GetRegistrationsByRangeController.as_view(),
        ),
        path(
            'users/registrations/compare/',
            GetRegistrationsComparisonController.as_view(),
        ),
        path(
            'users/without_visited_cities/',
            GetNumberOfUsersWithoutVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/total/',
            GetTotalVisitedCitiesVisitsController.as_view(),
        ),
        path(
            'visited_cities/unique/',
            GetUniqueVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/max_unique/',
            GetMaxQtyUniqueVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/max/',
            GetMaxQtyVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/average/',
            GetAverageQtyVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/average_unique/',
            GetAverageQtyUniqueVisitedCitiesController.as_view(),
        ),
        path(
            'visited_cities/added/range/',
            GetAddedVisitedCitiesByRangeController.as_view(),
        ),
        path(
            'visited_cities/added/compare/',
            GetAddedVisitedCitiesComparisonController.as_view(),
        ),
        # Страны
        path(
            'visited_countries/total/',
            GetTotalVisitedCountriesController.as_view(),
        ),
        path(
            'visited_countries/users/',
            GetUsersWithVisitedCountriesController.as_view(),
        ),
        path(
            'visited_countries/average/',
            GetAverageQtyVisitedCountriesController.as_view(),
        ),
        path(
            'visited_countries/max/',
            GetMaxQtyVisitedCountriesController.as_view(),
        ),
        path(
            'visited_countries/added/<int:days>/',
            GetAddedVisitedCountryController.as_view(),
        ),
        path(
            'visited_countries/added/chart/',
            GetAddedVisitedCountriesChartController.as_view(),
        ),
        path(
            'visited_countries/added/range/',
            GetAddedVisitedCountriesByRangeController.as_view(),
        ),
        path(
            'visited_countries/added/compare/',
            GetAddedVisitedCountriesComparisonController.as_view(),
        ),
        # Места
        path(
            'places/visited/total/',
            GetTotalVisitedPlacesController.as_view(),
        ),
        path(
            'places/visited/visited_only_total/',
            GetTotalVisitedOnlyPlacesController.as_view(),
        ),
        path(
            'places/visited/range/',
            GetPlacesByRangeController.as_view(),
        ),
        path(
            'places/visited/compare/',
            GetPlacesComparisonController.as_view(),
        ),
        path(
            'places/personal_collections/total/',
            GetPersonalCollectionsTotalController.as_view(),
        ),
        path(
            'places/personal_collections/public_total/',
            GetPublicPersonalCollectionsTotalController.as_view(),
        ),
        path(
            'places/personal_collections/range/',
            GetPersonalCollectionsByRangeController.as_view(),
        ),
        path(
            'places/personal_collections/compare/',
            GetPersonalCollectionsComparisonController.as_view(),
        ),
        # Блог
        path(
            'blog/articles/',
            GetBlogArticlesByPageController.as_view(),
        ),
        path(
            'blog/articles/last_added/',
            GetBlogLastAddedArticlesController.as_view(),
        ),
        path(
            'blog/articles/top_views/',
            GetBlogTopViewedArticlesController.as_view(),
        ),
        path(
            'blog/articles/added/range/',
            GetBlogArticlesAddedByRangeController.as_view(),
        ),
        path(
            'blog/articles/added/compare/',
            GetBlogArticlesAddedComparisonController.as_view(),
        ),
        path(
            'blog/articles/views/total/',
            GetBlogArticlesViewsTotalController.as_view(),
        ),
        path(
            'blog/articles/views/range/',
            GetBlogArticlesViewsByRangeController.as_view(),
        ),
        path(
            'blog/articles/views/compare/',
            GetBlogArticlesViewsComparisonController.as_view(),
        ),
        # Графики
        path(
            'users/registrations/chart/cumulative/',
            GetRegistrationsCumulativeChartController.as_view(),
        ),
        path(
            'visited_cities/by_user/chart/',
            GetVisitedCitiesByUserChartController.as_view(),
        ),
        path(
            'visited_cities/unique_by_user/chart/',
            GetUniqueVisitedCitiesByUserChartController.as_view(),
        ),
    ],
)

urlpatterns = [
    path('', include(router.urls)),
]
