# Generated by Django 4.2.13 on 2024-05-27 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'subscribe_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscribe_from_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь, который подписался',
                    ),
                ),
                (
                    'subscribe_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscribe_to_set',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь, на которого подписались',
                    ),
                ),
            ],
        ),
    ]
