# Generated by Django 4.2.24 on 2025-09-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0019_create_city_AB'),
        ('subscribe', '0002_alter_subscribe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcitynotification',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='city.city', verbose_name='Посещённый город'),
        ),
    ]
