fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: detect-private-key
    - id: name-tests-test
      exclude: create_db.py
    - id: no-commit-to-branch
    - id: detect-private-key

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff-format
