services:
  mg-postgres:
    container_name: mg-postgres
    image: postgres:14-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/some/
      POSTGRES_PASSWORD: password
    volumes:
       - moi-goroda-psql:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  moi-goroda-psql:
