# Generated by Django 4.2.3 on 2023-07-18 04:28

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Указанный заголовок новости будет отображатьсят только в админ-панели.<br>Пользователи его не увидят. Для них необходимо указывать заголовок новости в поле ниже.',
                        max_length=256,
                        verbose_name='Заголовок',
                    ),
                ),
                ('content', mdeditor.fields.MDTextField(verbose_name='Новость')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created'],
            },
        ),
    ]
