# Generated by Django 4.2.3 on 2023-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
