# Generated by Django 4.1.2 on 2023-04-21 13:12

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_created_alter_news_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
