# Generated by Django 4.1.2 on 2023-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Новость', max_length=256, verbose_name='Заголовок'),
        ),
    ]
