# Generated by Django 4.1.2 on 2023-04-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
