# Generated by Django 4.1.2 on 2023-05-21 15:35

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Новость'),
        ),
    ]
