# Generated by Django 4.2.24 on 2026-02-08 16:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_convert_markdown_content_to_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Новость'),
        ),
    ]
