# Generated by Django 4.1.2 on 2022-10-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Федеральный округ', 'verbose_name_plural': 'Федеральные округа'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['title'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='visitedcity',
            options={'verbose_name': 'Посещённый город', 'verbose_name_plural': 'Посещённые города'},
        ),
        migrations.AlterUniqueTogether(
            name='visitedcity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='region',
            name='iso3166',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Код ISO3166'),
        ),
        migrations.AlterField(
            model_name='city',
            name='coordinate_longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='coordinate_width',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='date_of_foundation',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Численность населения'),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.area', verbose_name='Федеральный округ'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='has_magnet',
            field=models.BooleanField(verbose_name='Наличие магнита'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='impression',
            field=models.TextField(blank=True, default='', verbose_name='Впечатления о городе'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
