# Generated by Django 4.1.2 on 2023-04-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '__first__'),
        ('travel', '0002_alter_area_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='area',
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='visitedcity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.region', verbose_name='Регион'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
