# Generated by Django 5.2.12 on 2026-05-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0031_cityuserphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedCityAddSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('sidebar', 'Сайдбар'), ('city_list', 'Список городов'), ('city_page', 'Страница города'), ('visited_cities_map', 'Карта посещённых городов'), ('region_map', 'Карта регионов'), ('collection_personal_map', 'Карта персональной коллекции'), ('collection_selected_map', 'Карта выбранной коллекции'), ('country_map', 'Карта страны'), ('api_unknown', 'API без подсказки'), ('unknown', 'Неизвестно')], db_index=True, max_length=64, verbose_name='Источник')),
                ('raw_hint', models.CharField(blank=True, default='', help_text='Например прежнее значение поля from в API', max_length=128, verbose_name='Сырой подсказка клиента')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Записано')),
                ('visited_city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='add_source_event', to='city.visitedcity', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Источник добавления посещённого города',
                'verbose_name_plural': 'Источники добавления посещённых городов',
                'indexes': [models.Index(fields=['surface', 'recorded_at'], name='analytics_v_surface_fa8e16_idx')],
            },
        ),
    ]
