# Generated by Django 5.2.12 on 2026-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial_visited_city_add_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedcityaddsource',
            name='surface',
            field=models.CharField(choices=[('sidebar', 'Сайдбар'), ('city_list', 'Список городов'), ('city_page', 'Страница города'), ('visited_cities_map', 'Карта посещённых городов'), ('region_map', 'Карта городов региона'), ('collection_personal_map', 'Карта персональной коллекции'), ('collection_selected_map', 'Карта коллекции сервиса'), ('api_unknown', 'API без подсказки'), ('unknown', 'Неизвестно')], db_index=True, max_length=64, verbose_name='Источник'),
        ),
    ]
