# Generated by Django 5.2.12 on 2026-05-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_group_user_alter_userconsent_options_and_more'),
        ('analytics', '0002_surface_labels_and_drop_country_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeSwitchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_slug', models.CharField(db_index=True, max_length=100, verbose_name='Slug региона')),
                ('mode_from', models.CharField(max_length=20, verbose_name='Режим ДО')),
                ('mode_to', models.CharField(max_length=20, verbose_name='Режим ПОСЛЕ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_switch_logs', to='account.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Переключение режима отображения',
                'verbose_name_plural': 'Переключения режима отображения',
                'indexes': [models.Index(fields=['region_slug', 'created_at'], name='analytics_m_region__1610b7_idx'), models.Index(fields=['user', 'created_at'], name='analytics_m_user_id_f13956_idx')],
            },
        ),
    ]
