# Generated by Django 5.2.12 on 2026-05-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_mode_switch_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeswitchlog',
            name='updated_at',
        ),
    ]
