# Generated by Django 5.2.12 on 2026-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_group_user_alter_userconsent_options_and_more'),
        ('analytics', '0004_remove_mode_switch_log_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='modeswitchlog',
            index=models.Index(fields=['mode_to', 'mode_from', 'created_at'], name='analytics_m_mode_to_34ded1_idx'),
        ),
    ]
