# Generated by Django 4.2.3 on 2023-07-24 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={
                'ordering': ['title'],
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
    ]
