# Generated by Django 4.2.24 on 2025-10-17 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0002_alter_collection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='collection.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная коллекция',
                'verbose_name_plural': 'Избранные коллекции',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'collection')},
            },
        ),
    ]
