# Generated by Django 4.2.24 on 2025-12-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('city', '0021_change_created_at_to_auto_now_add'),
        ('collection', '0003_favoritecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_public', models.BooleanField(default=False, help_text='Если коллекция публичная, то пользователь сможет поделиться ссылкой на неё и любой желающий сможет посмотреть города этой коллекции', verbose_name='Публичная коллекция')),
                ('city', models.ManyToManyField(related_name='personal_collections_list', to='city.city', verbose_name='Города')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_collections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Персональная коллекция',
                'verbose_name_plural': 'Персональные коллекции',
                'ordering': ['-created_at'],
            },
        ),
    ]
