# Generated by Django 4.2.24 on 2025-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_personalcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcollection',
            name='is_copied',
            field=models.BooleanField(default=False, help_text='Указывает, была ли коллекция скопирована из другой коллекции', verbose_name='Скопированная коллекция'),
        ),
    ]
