# Generated by Django 4.2.17 on 2025-04-29 11:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отображаемый текст')),
                ('url', models.URLField(verbose_name='URL ссылки')),
                ('marking', models.CharField(max_length=255, verbose_name='Маркировка рекламы')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет ссылки')),
            ],
        ),
    ]
