# Generated by Django 4.2.17 on 2025-04-29 11:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkadvertisement',
            options={'verbose_name': 'Рекламная ссылка', 'verbose_name_plural': 'Рекламные ссылки'},
        ),
        migrations.RemoveField(
            model_name='linkadvertisement',
            name='marking',
        ),
        migrations.AddField(
            model_name='linkadvertisement',
            name='icon_class',
            field=models.CharField(default='hello', help_text='CSS-класс иконки FontAwesome, например: fa-solid fa-star', max_length=50, verbose_name='Класс FontAwesome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkadvertisement',
            name='legal_marking',
            field=models.CharField(default=1, help_text='Текст, который будет отображаться как юридическая маркировка рекламы, например: "Реклама. ООО «Компания». ИНН 1234567890"', max_length=255, verbose_name='Маркировка рекламы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkadvertisement',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Цвет текста ссылки в формате HEX, например: #FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет ссылки'),
        ),
        migrations.AlterField(
            model_name='linkadvertisement',
            name='title',
            field=models.CharField(help_text='Текст, который будет виден пользователю как подпись к ссылке', max_length=255, verbose_name='Отображаемый текст'),
        ),
        migrations.AlterField(
            model_name='linkadvertisement',
            name='url',
            field=models.URLField(help_text='Полный адрес перехода, например: https://example.com', verbose_name='URL ссылки'),
        ),
    ]
