# Generated by Django 4.2.20 on 2025-05-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0002_alter_linkadvertisement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(verbose_name='Дата, до которой реклама не показывается')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому не показывается реклама')),
            ],
            options={
                'verbose_name': 'Исключённый пользователь',
                'verbose_name_plural': 'Исключённые пользователи',
            },
        ),
    ]
