# Generated by Django 4.2.21 on 2025-06-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisementexception'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkAdvertisement',
        ),
    ]
