# Generated by Django 4.2.24 on 2026-02-08 16:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
    ]
