# Generated by Django 4.2.24 on 2026-02-09 22:42

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):  # noqa: ARG001
    BlogTag = apps.get_model('blog', 'BlogTag')
    for tag in BlogTag.objects.all():
        base = slugify(tag.name, allow_unicode=True) or 'tag'
        base = base[:60].rstrip('-')
        slug = base
        suffix = 0
        while BlogTag.objects.filter(slug=slug).exclude(pk=tag.pk).exists():
            suffix += 1
            slug = f'{base}-{suffix}'[:60]
        tag.slug = slug
        tag.save(update_fields=['slug'])


def noop(apps, schema_editor):  # noqa: ARG001
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_use_tinymce'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='Слаг для URL'),
        ),
        migrations.RunPython(populate_slug, noop),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Слаг для URL'),
        ),
    ]
