# Generated by Django 4.2.24 on 2026-02-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_blogarticle_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='meta_description',
            field=models.CharField(help_text='Текст для мета-тега description на странице статьи (рекомендуется до 160 символов)', max_length=256, verbose_name='Описание для meta description'),
        ),
    ]
