# Generated by Django 4.2.17 on 2025-01-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='place.typeobject', verbose_name='Тип объекта'),
        ),
    ]
