# Generated by Django 4.2.24 on 2026-02-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0002_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_visited',
            field=models.BooleanField(default=True, verbose_name='Место посещено'),
        ),
        migrations.CreateModel(
            name='PlaceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная коллекция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_collections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коллекция мест',
                'verbose_name_plural': 'Коллекции мест',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='place.placecollection', verbose_name='Коллекция'),
        ),
    ]
