# Generated by Django 4.2.17 on 2025-01-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_type_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='place.typeobject', verbose_name='Тип объекта'),
            preserve_default=False,
        ),
    ]
