from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from blog.models import BlogArticle, BlogArticleView, BlogTag


class BlogTagModelTests(TestCase):
    def test_str_returns_name(self) -> None:
        tag = BlogTag.objects.create(name='Путешествия', slug='puteshestviya')
        self.assertEqual(str(tag), 'Путешествия')

    def test_slug_autogenerated_if_empty(self) -> None:
        tag = BlogTag.objects.create(name='Города России', slug='')
        self.assertTrue(tag.slug)
        self.assertLessEqual(len(tag.slug), 60)
        # slugify(..., allow_unicode=True) даёт кириллический slug
        self.assertIn('россии', tag.slug)

    def test_slug_not_overwritten_if_set(self) -> None:
        tag = BlogTag.objects.create(name='Авторский тег', slug='custom-slug')
        tag.name = 'Новое имя'
        tag.save()
        self.assertEqual(tag.slug, 'custom-slug')

    def test_slug_made_unique(self) -> None:
        # name уникален, поэтому берём разные имена, дающие один и тот же slug
        first = BlogTag.objects.create(name='Test', slug='')
        second = BlogTag.objects.create(name='test', slug='')
        self.assertNotEqual(first.slug, second.slug)
        self.assertTrue(second.slug.startswith('test'))


class BlogArticleModelTests(TestCase):
    def test_str_returns_title(self) -> None:
        article = BlogArticle.objects.create(
            title='Тестовая статья',
            content='<p>Контент</p>',
            meta_description='Описание тестовой статьи',
            is_published=True,
        )
        self.assertEqual(str(article), 'Тестовая статья')

    def test_get_absolute_url_uses_named_url(self) -> None:
        article = BlogArticle.objects.create(
            title='URL статья',
            content='<p>Контент</p>',
            meta_description='Описание URL статьи',
            is_published=True,
        )
        expected = reverse('blog-article-detail', kwargs={'slug': article.slug})
        self.assertEqual(article.get_absolute_url(), expected)


class BlogArticleViewModelTests(TestCase):
    def setUp(self) -> None:
        self.user = User.objects.create_user(username='john', password='secret')
        self.article = BlogArticle.objects.create(
            title='Просматриваемая статья',
            content='<p>Текст</p>',
            meta_description='Описание просматриваемой статьи',
            is_published=True,
        )

    def test_str_with_authenticated_user(self) -> None:
        view = BlogArticleView.objects.create(
            article=self.article,
            user=self.user,
            ip_address='127.0.0.1',
        )
        text = str(view)
        self.assertIn('Просматриваемая статья', text)
        self.assertIn('john', text)

    def test_str_with_guest_user(self) -> None:
        view = BlogArticleView.objects.create(
            article=self.article,
            user=None,
            ip_address='127.0.0.1',
        )
        text = str(view)
        self.assertIn('Просматриваемая статья', text)
        self.assertIn('Гость', text)
