# Generated by Django 4.2.3 on 2023-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='iso3166',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код ISO3166'),
        ),
    ]
