# Generated by Django 4.2.21 on 2025-06-06 09:59

from django.db import migrations, models
import django.db.models.deletion

from country.models import Country
from region.models import Region, Area


def set_country(apps, schema_editor):
    Region.objects.all().update(country=Country.objects.get(pk=171))
    Area.objects.all().update(country=Country.objects.get(pk=171))


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0005_country_is_member_of_un_country_owner'),
        ('region', '0002_alter_region_iso3166'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='country.country',
                verbose_name='Страна',
            ),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='country.country',
                verbose_name='Страна',
            ),
        ),
        migrations.RunPython(set_country),
    ]
