# Generated by Django 4.1.2 on 2023-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_alter_area_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='iso3166',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='Код ISO3166'),
        ),
    ]
