# Generated by Django 4.1.2 on 2023-04-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_region_iso3166'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('title', 'type')},
        ),
    ]
