# Generated by Django 4.2.21 on 2025-06-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_alter_area_country_alter_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.area', verbose_name='Федеральный округ'),
        ),
    ]
