# Generated by Django 4.2.21 on 2025-06-17 11:18

from django.db import migrations, models
from django.db.migrations import RunPython


def fill_full_name(apps, schema_editor):
    Region = apps.get_model('region', 'Region')

    for region in Region.objects.all():
        if region.type == 'G':
            full_name = region.title
        elif region.type == 'R':
            if region.title in [
                'Кабардино-Балкарская',
                'Карачаево-Черкесская',
                'Удмуртская',
                'Чеченская',
                'Чувашская',
            ]:
                full_name = f'{region.title} республика'
            else:
                full_name = region.title
        else:
            type_display = {
                'O': 'область',
                'K': 'край',
                'AOk': 'автономный округ',
                'R': 'республика',
                'G': 'город федерального значения',
                'AOb': 'автономная область',
            }.get(region.type, region.type)

            full_name = f'{region.title} {type_display.lower()}'

        region.full_name = full_name
        region.save()


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0005_alter_region_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное название'),
        ),
        RunPython(fill_full_name),
    ]
