# ---------------------------------------------
#
# Copyright © Egor Vavilov (Shecspi)
# Licensed under the Apache License, Version 2.0
#
# ----------------------------------------------

"""
Django settings for djangoProject project.

Generated by 'django-admin_panel startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dmr.settings import Settings
from dotenv import load_dotenv
from typing_extensions import TypedDict

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем .env файл из директории с settings.py
load_dotenv(Path(__file__).resolve().parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'colorfield',
    'main_page',
    'account.apps.AuthConfig',
    'city',
    'news',
    'blog',
    'region',
    'collection',
    'mathfilters',
    'markdownify',
    'tinymce',
    'django_ckeditor_5',
    'storages',
    'dashboard',
    'share.apps.ShareConfig',
    'subscribe',
    'rest_framework',
    'country',
    'place',
    'advertisement',
    'admin_auto_filters',
    'premium',
    'dmr',
    'ui_demo.apps.UiDemoConfig',
    'analytics.apps.AnalyticsConfig',
    'geo_polygons.apps.GeoPolygonsConfig',
    'django_prometheus',
]


MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

# Debug toolbar находится в DEV-зависимостях, поэтому на продакшене он не устанавливается.
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']

ROOT_URLCONF = 'MoiGoroda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MoiGoroda.context_processors.general_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'MoiGoroda.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE'),
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}

# Redis Cache
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_SOCKET_TIMEOUT_SECONDS = float(os.getenv('REDIS_SOCKET_TIMEOUT_SECONDS', '1'))


def build_redis_cache_config(
    *,
    location: str,
    ignore_exceptions: bool = False,
) -> dict[str, object]:
    """Возвращает конфигурацию django-redis с явной failure policy."""
    options: dict[str, object] = {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        'SOCKET_CONNECT_TIMEOUT': REDIS_SOCKET_TIMEOUT_SECONDS,
        'SOCKET_TIMEOUT': REDIS_SOCKET_TIMEOUT_SECONDS,
    }
    if ignore_exceptions:
        options['IGNORE_EXCEPTIONS'] = True

    return {
        'BACKEND': 'django_prometheus.cache.backends.redis.RedisCache',
        'LOCATION': location,
        'OPTIONS': options,
    }


CACHES = {
    'default': build_redis_cache_config(
        location=f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
        ignore_exceptions=True,
    ),
    'sessions': build_redis_cache_config(location=f'redis://{REDIS_HOST}:{REDIS_PORT}/2'),
    'stats': build_redis_cache_config(
        location=f'redis://{REDIS_HOST}:{REDIS_PORT}/3',
        ignore_exceptions=True,
    ),
}

# Session backend
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 неделя

# Определяем, запущены ли тесты
TESTING = 'test' in sys.argv or 'pytest' in sys.modules or os.getenv('TESTING') == 'True'

if TESTING:
    # Django test runner переопределит DEBUG=False, поэтому vite_asset проверяет TESTING напрямую
    DEBUG = True
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-cache',
        },
        'sessions': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-sessions-cache',
        },
        'stats': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-stats-cache',
        },
    }

# django-prometheus: экспорт метрик БД в Prometheus
PROMETHEUS_METRICS_EXPORT_DATABASE_METRICS = True

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = os.getenv('TIME_ZONE')

USE_I18N = True

USE_TZ = os.getenv('USE_TZ') == 'True'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'frontend'),  # Для доступа к исходным CSS в dev-режиме
]
STATIC_ROOT = os.getenv('STATIC_ROOT')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/city/all/list'
LOGOUT_REDIRECT_URL = '/'

INTERNAL_IPS = ['127.0.0.1', '0.0.0.0']

LOGIN_URL = '/account/signin'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'

SERVER_EMAIL = os.getenv('SERVER_EMAIL')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
ADMINS = [
    (os.getenv('ADMIN_NAME'), os.getenv('ADMIN_EMAIL')),
]

YOOKASSA_SHOP_ID = os.getenv('YOOKASSA_SHOP_ID')
YOOKASSA_SECRET_KEY = os.getenv('YOOKASSA_SECRET_KEY')
# Проверка IP для вебхука (False — отключить, например для локальной разработки)
YOOKASSA_WEBHOOK_IP_VERIFICATION = os.getenv('YOOKASSA_WEBHOOK_IP_VERIFICATION', 'True') == 'True'

LOG_FIlE_PATH = os.path.join(BASE_DIR, 'logs/log.log')
LOG_PREMIUM_PAYMENTS_PATH = os.path.join(BASE_DIR, 'logs/premium_payments.log')
LOG_CRON_PATH = os.path.join(BASE_DIR, 'logs/cron.log')
if not os.path.exists(os.path.dirname(LOG_FIlE_PATH)):
    os.mkdir(os.path.dirname(LOG_FIlE_PATH))
if not os.path.exists(LOG_FIlE_PATH):
    open(LOG_FIlE_PATH, 'a').close()
if not os.path.exists(LOG_PREMIUM_PAYMENTS_PATH):
    open(LOG_PREMIUM_PAYMENTS_PATH, 'a').close()
if not os.path.exists(LOG_CRON_PATH):
    open(LOG_CRON_PATH, 'a').close()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        # Отправка писем только при DEBUG = False
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'add_default_log_context': {
            '()': 'services.logging_filters.DefaultLogContextFilter',
        },
    },
    'formatters': {
        'detail_app': {
            'format': '%(levelname)-8s %(asctime)-22s %(IP)-18s %(user)-10s %(message)-s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detail_django': {
            'format': '%(levelname)-8s %(asctime)-22s INTERNAL           DJANGO     %(message)-s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {'format': '%(levelname)-8s %(asctime)-25s %(message)s'},
        'premium_payments': {
            'format': '%(levelname)-8s %(asctime)-22s %(IP)-18s %(user)-10s %(message)-s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json_app': {
            'class': 'pythonjsonlogger.json.JsonFormatter',
            'format': '%(levelname)s %(asctime)s %(IP)s %(user)s %(name)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json_simple': {
            'class': 'pythonjsonlogger.json.JsonFormatter',
            'format': '%(levelname)s %(asctime)s %(message)s',
        },
    },
    'handlers': {
        # Запись в файл логов приложения
        # Только при DEBUG=False
        'to_file_app': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'json_app',
            'filename': LOG_FIlE_PATH,
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
        },
        # Запись в файл логов Django
        # Только при DEBUG=False
        'to_file_django': {
            'level': 'WARNING',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'formatter': 'json_simple',
            'filename': LOG_FIlE_PATH,
        },
        # Отправка писем с ошибками на почту
        # Только при DEBUG=False
        'to_email_general': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        # Вывод в консоль логов приложения
        # только при DEBUG=True
        'to_console_app': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'detail_app',
        },
        # Вывод в консоль логов Django
        # только при DEBUG=True
        'to_console_django': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'detail_django',
        },
        # DEBUG-логи cache helper'ов используют общий формат с fallback IP/user.
        'to_console_cache': {
            'level': 'DEBUG',
            'filters': ['require_debug_true', 'add_default_log_context'],
            'class': 'logging.StreamHandler',
            'formatter': 'detail_app',
        },
        # Файл только с информацией о платежах (вебхук YooKassa)
        'to_file_premium_payments': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'json_app',
            'filename': LOG_PREMIUM_PAYMENTS_PATH,
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 3,
        },
        # Платежи в консоль — только при DEBUG=True
        'to_console_premium_payments': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'premium_payments',
        },
        # Файл только с логами периодических задач (cron)
        'to_file_cron': {
            'level': 'INFO',
            'filters': ['add_default_log_context'],
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'json_app',
            'filename': LOG_CRON_PATH,
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 3,
        },
        # Консоль для логов cron — только при DEBUG=True
        'to_console_cron': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Базовый логгер. Используется для логирования действий внутри приложения
        'base': {
            'level': 'INFO',
            'propogate': True,
            'handlers': ['to_console_app', 'to_file_app', 'to_email_general'],
        },
        # Логгер для account.views (в т.ч. регистрация пользователей)
        'account.views': {
            'level': 'INFO',
            'propogate': True,
            'handlers': ['to_console_app', 'to_file_app'],
        },
        # Логгер для перехватывания логирования Django
        'django': {
            'level': 'INFO',
            'propogate': True,
            'handlers': ['to_console_django', 'to_file_django'],
        },
        # DEBUG-логи cache helper'ов только в консоль при DEBUG=True
        'services.cache': {
            'level': 'DEBUG',
            'propagate': False,
            'handlers': ['to_console_cache'],
        },
        # Только платежи (вебхук YooKassa) — файл и в консоль при DEBUG
        'premium.webhook': {
            'level': 'INFO',
            'propagate': False,
            'handlers': ['to_file_premium_payments', 'to_console_premium_payments'],
        },
        # Периодические задания (cron): истечение подписок и т.п.
        'premium.cron': {
            'level': 'INFO',
            'propagate': False,
            'handlers': ['to_file_cron', 'to_console_cron'],
        },
    },
}

MEDIA_URL = 'https://s3.twcstorage.ru/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Markdownify
MARKDOWNIFY = {
    'default': {
        'WHITELIST_TAGS': [
            # Протестированные теги
            'a',
            'blockquote',
            'code',
            'img',
            'em',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'strong',
            # Непротестированные теги
            'li',
            'ol',
            'p',
            'ul',
        ],
        'WHITELIST_ATTRS': ['href', 'src', 'alt'],
    },
    'only_links': {
        'WHITELIST_TAGS': [
            'a',
            'br',
            'em',
            'p',
            'h1',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'hr',
            'strong',
            'li',
            'ol',
            'ul',
        ]
    },
}

# Тайловые серверы (например OpenStreetMap) могут требовать Referer.
# `same-origin` скрывает referer на cross-origin запросах и приводит к блокировке тайлов.
SECURE_REFERRER_POLICY = os.getenv(
    'SECURE_REFERRER_POLICY',
    'strict-origin-when-cross-origin',
)

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'

URL_S3_GEO_POLYGONS = os.getenv('URL_S3_GEO_POLYGONS')

_DEFAULT_OVERPASS_ENDPOINTS = (
    'https://overpass-api.de/api/interpreter',
    'https://overpass.kumi.systems/api/interpreter',
    'https://overpass.openstreetmap.ru/api/interpreter',
)
_overpass_endpoints_env = os.getenv('OVERPASS_ENDPOINTS', '')
OVERPASS_ENDPOINTS = (
    [item.strip() for item in _overpass_endpoints_env.split(',') if item.strip()]
    if _overpass_endpoints_env.strip()
    else list(_DEFAULT_OVERPASS_ENDPOINTS)
)

PRIVACY_POLICY_VERSION = os.getenv('PRIVACY_POLICY_VERSION')

ALLOWED_HOSTS_FOR_EMBEDDED_REGION_MAPS = (
    ' '.join(os.getenv('ALLOWED_HOSTS_FOR_EMBEDDED_REGION_MAPS', '').split(','))
    if os.getenv('ALLOWED_HOSTS_FOR_EMBEDDED_REGION_MAPS')
    else ''
)

# TinyMCE

TINYMCE_FILEBROWSER = False

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'menubar': False,
    'plugins': 'advlist autolink lists link image charmap anchor searchreplace visualblocks code '
    'fullscreen insertdatetime media table help wordcount',
    'toolbar': 'undo redo | blocks | bold italic | alignleft aligncenter alignright | '
    'bullist numlist outdent indent | link image blog_carousel | '
    'rtb_banner_inside_article_1 rtb_banner_inside_article_2 rtb_banner_inside_article_3 | removeformat | help',
    'content_style': (
        'body { font-family:Helvetica,Arial,sans-serif; font-size:14px } '
        '.ad-placeholder-rtb-banner { '
        'display: block; min-height: 2.5em; margin: 1em 0; '
        'background: #fff3cd; border: 1px dashed #856404; border-radius: 4px; '
        'color: #856404; padding: 0.5em 0.75em; font-size: 13px; '
        '} '
        '.ad-placeholder-rtb-banner[data-ad="rtb_banner_inside_article_1"]::before { content: "Рекламный блок 1"; font-weight: 600; } '
        '.ad-placeholder-rtb-banner[data-ad="rtb_banner_inside_article_2"]::before { content: "Рекламный блок 2"; font-weight: 600; } '
        '.ad-placeholder-rtb-banner[data-ad="rtb_banner_inside_article_3"]::before { content: "Рекламный блок 3"; font-weight: 600; } '
        '.ad-placeholder-rtb-banner:not([data-ad])::before { content: "Рекламный блок"; font-weight: 600; } '
        '.mg-blog-carousel { '
        'display: block; margin: 1em 0; padding: 0.75em; '
        'background: #e8f4fd; border: 1px dashed #0d6efd; border-radius: 6px; '
        '} '
        '.mg-blog-carousel::before { '
        'content: "Карусель фотографий"; display: block; font-weight: 600; '
        'font-size: 13px; color: #0d6efd; margin-bottom: 0.5em; '
        '} '
        '.mg-blog-carousel img { '
        'display: inline-block; max-width: 120px; max-height: 80px; '
        'object-fit: cover; margin: 0 4px 4px 0; border-radius: 4px; vertical-align: top; '
        '} '
        '.mg-blog-carousel[data-mg-caption]::after { '
        'content: attr(data-mg-caption); display: block; clear: both; '
        'text-align: center; font-size: 12px; line-height: 1.25; color: #6b7280; '
        'margin-top: 0.5em; padding: 0 0.25em; '
        '} '
        'body p:has(> img:not(.mg-blog-carousel img)), '
        'body figure:has(> img:not(.mg-blog-carousel img)) { '
        'display: block; width: 100%; margin: 0 0 1em; text-align: center; '
        '} '
        'body p[data-mg-caption]:not(:has(.mg-blog-carousel))::after, '
        'body figure[data-mg-caption]:not(:has(.mg-blog-carousel))::after { '
        'content: attr(data-mg-caption); display: block; clear: both; '
        'text-align: center; font-size: 12px; line-height: 1.25; color: #6b7280; '
        'margin-top: 0.25em; padding: 0 0.25em; '
        '} '
        'body img:not(.mg-blog-carousel img) { '
        'display: block !important; float: none !important; clear: both !important; '
        'margin: 0.5em auto !important; '
        'max-width: 200px !important; max-height: 200px !important; '
        'width: auto !important; height: auto !important; '
        '} '
        'body img:not(.mg-blog-carousel img)[data-mg-caption] { '
        'display: block; margin-left: auto; margin-right: auto; '
        '} '
        'body img:not(.mg-blog-carousel img)[data-mg-caption]::after { '
        'content: attr(data-mg-caption); display: block; '
        'text-align: center; font-size: 12px; line-height: 1.25; color: #6b7280; '
        'margin-top: 0.25em; padding: 0 0.25em; '
        '} '
        'img[data-mg-content-sized] { max-width: 100%; height: auto; }'
    ),
    'images_upload_url': '/tinymce/upload-image/',
    'images_upload_handler': 'djangoTinyMCEImagesUploadHandler',
    'automatic_uploads': True,
    'setup': 'djangoTinyMCESetup',
    # Сохранять div-маркеры рекламы и карусели
    'extended_valid_elements': (
        'div[class|data-ad|contenteditable|data-mg-blog-carousel|data-mg-caption],'
        'p[data-mg-caption],figure[data-mg-caption],'
        'img[class|src|alt|width|height|data-mg-content-sized|data-mg-caption]'
    ),
}

TINYMCE_EXTRA_MEDIA = {
    'js': [
        'tinymce/js/tinymce_csrf_upload.js',
        'tinymce/js/tinymce_rtb_button.js',
        'tinymce/js/tinymce_blog_carousel_multiselect.js',
        'tinymce/js/tinymce_content_image.js',
        'tinymce/js/tinymce_setup.js',
    ],
}

# Django Storage
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
AWS_USERS_CITY_PHOTOS_BUCKET_NAME = os.getenv('AWS_USERS_CITY_PHOTOS_BUCKET_NAME')
AWS_USERS_CITY_PHOTOS_REGION_NAME = (
    os.getenv('AWS_USERS_CITY_PHOTOS_REGION_NAME') or AWS_S3_REGION_NAME
)
AWS_USERS_CITY_PHOTOS_URL_EXPIRE_SECONDS = int(
    os.getenv('AWS_USERS_CITY_PHOTOS_URL_EXPIRE_SECONDS', '120')
)
CITY_USER_PHOTOS_LIMIT = int(os.getenv('CITY_USER_PHOTOS_LIMIT', '10'))
CITY_USER_PHOTO_MAX_UPLOAD_MB = int(os.getenv('CITY_USER_PHOTO_MAX_UPLOAD_MB', '15'))
CITY_USER_PHOTO_MAX_UPLOAD_BYTES = CITY_USER_PHOTO_MAX_UPLOAD_MB * 1024 * 1024
CITY_USER_PHOTO_MAX_PIXELS = int(os.getenv('CITY_USER_PHOTO_MAX_PIXELS', '40000000'))
AWS_STANDARD_CITY_PHOTOS_BUCKET_NAME = os.getenv('AWS_STANDARD_CITY_PHOTOS_BUCKET_NAME')
AWS_STANDARD_CITY_PHOTOS_REGION_NAME = (
    os.getenv('AWS_STANDARD_CITY_PHOTOS_REGION_NAME') or AWS_S3_REGION_NAME
)
AWS_STANDARD_CITY_PHOTOS_URL_EXPIRE_SECONDS = int(
    os.getenv('AWS_STANDARD_CITY_PHOTOS_URL_EXPIRE_SECONDS', '86400')
)
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=31536000',  # 1 год
}

# Настройки Django Modern Rest


class Error(TypedDict):
    detail: str


DMR_SETTINGS: dict[Settings, list[Error]] = {
    Settings.responses: [],
}
