# Generated by Django 4.2.24 on 2026-02-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Системное имя тарифа')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание тарифа')),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в месяц')),
                ('price_year', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в год')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тариф премиум-подписки',
                'verbose_name_plural': 'Тарифы премиум-подписки',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(choices=[('monthly', 'Месячная'), ('yearly', 'Годовая')], max_length=10, verbose_name='Период оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает активации'), ('active', 'Активна'), ('canceled', 'Отменена'), ('expired', 'Истекла')], default='pending', max_length=10, verbose_name='Статус подписки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Автопродление')),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа в YooKassa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='premium.premiumplan', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Премиум-подписка пользователя',
                'verbose_name_plural': 'Премиум-подписки пользователей',
            },
        ),
        migrations.CreateModel(
            name='PremiumPlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Преимущество')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='premium.premiumplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Преимущество тарифа',
                'verbose_name_plural': 'Преимущества тарифа',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID платежа в YooKassa')),
                ('amount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('billing_period', models.CharField(choices=[('monthly', 'Месячная'), ('yearly', 'Годовая')], max_length=10, verbose_name='Период оплаты')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting_for_capture', 'Ожидает списания'), ('succeeded', 'Успешно оплачен'), ('canceled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные ответа YooKassa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='premium.premiumplan', verbose_name='Тариф')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='premium.premiumsubscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж премиум-подписки',
                'verbose_name_plural': 'Платежи премиум-подписки',
            },
        ),
        migrations.AddConstraint(
            model_name='premiumsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_premium_subscription_per_user'),
        ),
        migrations.AddIndex(
            model_name='premiumpayment',
            index=models.Index(fields=['yookassa_payment_id'], name='premium_pre_yookass_55e90a_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumpayment',
            index=models.Index(fields=['user'], name='premium_pre_user_id_11ef82_idx'),
        ),
    ]
