# Generated by Django 4.2.24 on 2026-02-28 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(db_index=True, max_length=100, verbose_name='ID платежа в YooKassa')),
                ('status', models.CharField(max_length=20, verbose_name='Статус в уведомлении')),
                ('raw_payload', models.JSONField(verbose_name='Входящий JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='premium.premiumpayment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Лог вебхука платежа',
                'verbose_name_plural': 'Логи вебхуков платежей',
                'ordering': ('-created_at',),
            },
        ),
    ]
