# Generated by Django 4.2.24 on 2026-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_webhook_log_int_id_no_yookassa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='raw_response',
        ),
        migrations.AlterField(
            model_name='premiumpaymentwebhooklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
