# Generated by Django 4.2.24 on 2026-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_remove_premium_payment_raw_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='billing_period',
            field=models.CharField(choices=[('monthly', '1 месяц'), ('yearly', '1 год')], max_length=10, verbose_name='Период оплаты'),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', '1 месяц'), ('yearly', '1 год')], max_length=10, verbose_name='Период оплаты'),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает активации'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('canceled', 'Отменена'), ('expired', 'Истекла')], default='pending', max_length=10, verbose_name='Статус подписки'),
        ),
    ]
