# Generated by Django 4.2.24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0006_add_scheduled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscription',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает активации'),
                    ('active', 'Активна'),
                    ('paused', 'Приостановлена'),
                    ('scheduled', 'Запланирована (после окончания текущей)'),
                    ('interrupted', 'Прерванная'),
                    ('canceled', 'Отменена'),
                    ('expired', 'Истекла'),
                ],
                default='pending',
                max_length=12,
                verbose_name='Статус подписки',
            ),
        ),
    ]
