# Generated by Django 4.2.24 on 2026-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0007_add_interrupted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='confirmation_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL для оплаты (confirmation_url из YooKassa)'),
        ),
    ]
