name: Deploy to the server
on:
    push:
      branches: [ "master" ]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEV__LOCAL_PATH }}
            git pull origin master
            git checkout master
            ${{ secrets.DEV__POETRY_PATH }} run python3 manage.py makemigrations
            ${{ secrets.DEV__POETRY_PATH }} run python3 manage.py migrate
            export POETRY_PATH=${{ secrets.DEV__POETRY_PATH }}
            chmod +x ./scripts/collectstatic.sh
            ./scripts/collectstatic.sh
            chmod -x ./scripts/collectstatic.sh
            chmod +x ./scripts/restart.sh
            export SUDO_PASSWORD=${{ secrets.DEV__SUDO_PASSWORD }}
            ./scripts/restart.sh
            chmod -x ./scripts/restart.sh
